"""correo unico en usuarios

Revision ID: 37e09c3bcc17
Revises: 56acf0546194
Create Date: 2026-09-20 14:46:14.742604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e09c3bcc17'
down_revision: Union[str, Sequence[str], None] = '56acf0546194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuarios', ['correo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    # ### end Alembic commands ###
