"""agregar ciudad a usuarios

Revision ID: 47e20a3d7e7f
Revises: d8848d64e7cc
Create Date: 2026-09-04 19:45:32.414558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e20a3d7e7f'
down_revision: Union[str, Sequence[str], None] = 'd8848d64e7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ciudad', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'ciudad')
    # ### end Alembic commands ###
