"""agregar rol a usuarios

Revision ID: 56acf0546194
Revises: e76e34cf8d6b
Create Date: 2026-09-18 06:38:26.115945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56acf0546194'
down_revision: Union[str, Sequence[str], None] = 'e76e34cf8d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 1. Crear temporalmente la columna permitiendo NULL
    op.add_column(
        'usuarios',
        sa.Column('rol', sa.String(), nullable=True)
    )

    # 2. Dar rol a los usuarios que ya existen
    op.execute(
        "UPDATE usuarios SET rol = 'user' WHERE rol IS NULL"
    )

    # 3. Una vez que todos tienen rol, prohibir NULL
    op.alter_column(
        'usuarios',
        'rol',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'rol')
    # ### end Alembic commands ###
