"""agregar telefono a usuarios

Revision ID: d8848d64e7cc
Revises: 3965e7b974fd
Create Date: 2026-09-04 05:45:11.165793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8848d64e7cc'
down_revision: Union[str, Sequence[str], None] = '3965e7b974fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('telefono', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'telefono')
    # ### end Alembic commands ###
