"""agregar password_hash a usuarios

Revision ID: e76e34cf8d6b
Revises: 47e20a3d7e7f
Create Date: 2026-09-13 19:39:23.749429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76e34cf8d6b'
down_revision: Union[str, Sequence[str], None] = '47e20a3d7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###
